apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b8g4avzie-nodejs
  janus-idp.io/tekton: b8g4avzie-nodejs
  backstage.io/kubernetes-id: b8g4avzie-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b8g4avzie-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
